### ISSUE TITLE
how to train instance segmentation?

### ISSUE THREAD

**Issue by xxxzhi** [aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping#1]
Could you provide training demo code?

**Comment by aimerykong** [comment]
Hi,

Thank for your interest.

I've made two demos ready --
1) The first demo provides training and some visualization scripts on MNIST
dataset. You can look into the folder as below to generate dataset and
train the model. You can also download some models to resume training and
visualize the result.
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/tree/master/demo1_tutorial_instance_segmentation
2) The second is to visualize to understand the gradient through mean
shift. Please look into the folder as below to run the scripts.
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/tree/master/demo5_analysis_MShift_gradient

Readme files in the two folders should provide a guide on how to run the
scripts.

Please let me know if you have further questions or problems in running the
scripts. As for other scripts, I will upload and make them as neat as
possible in the near future.

Thanks again!

Regards,
Shu

**Comment by xxxzhi** [comment]
oh, thank you!
