### ISSUE TITLE
Code for instance-level segmentation

### ISSUE THREAD

**Issue by eugenelawrence** [aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping#2]
Will you provide the demo for instance-level segmentation on PASCAL VOC2012 dataset?

**Comment by aimerykong** [comment]
Hi, Lawrence,

For instance segmentation I've released a model trained on PASCAL VOC2012
plus the SBD dataset as augmentation (
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/tree/master/demo3_objectness_proposal_detection
)

Note that, this model is different from what used in the paper in that, the
released model 2x upsamples the feature maps, resulting into 4x smaller
resolution compared to the input images; while what reported in the paper
produces results of 8x smaller resolution. Meanwhile, I'm pursuing further
by training over COCO dataset now. My plan is to release a model trained on
COCO dataset later.

Moreover, I opt not to manage the repository too much to include the
semantic model which is used for semantic instance segmentation. This will
be merged into a COCO-trained model with Faster RCNN flavor that shares the
backbone.

Thanks for your interest.
