### ISSUE TITLE
Mean Shift Clustering Memory Issue

### ISSUE THREAD

**Issue by matlabbaltam** [aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping#3]
So how do you apply the matrix form of mean shift on real images without memory issue? Take a 480 by 320 image as an example. To calculate K matrix in equation(3) in your paper, the size of it will be 153600 by 153600 and it will take up about 90Gb memory! How do you solve this memory issue?

**Comment by aimerykong** [comment]
Thanks for your interest.

We adopt uniformly random sampling to deal with this. Specifically, in each
iteration (dealing each image), we randomly choose a small portion of
pixels fed to the loss. Please have a look at our implementation following
the link below --
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/blob/master/demo3_objectness_proposal_detection/cosineSimilarity_randSample.m#L28

Hope this helps.
