### ISSUE TITLE
von Mises Fisher mean shift

### ISSUE THREAD

**Issue by utkarshgaur** [aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping#4]
Looks like you are using Euclidean distance in your demo kernel matrix:
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/blob/master/demo5_analysis_MShift_gradient/simulation07_1D_GBMS_1step_trajectory.m#L149

However the paper mentions using von Mises-Fisher kernel. Can you point me to where you are computing the cosine distance based vMF kernel? thanks

**Comment by aimerykong** [comment]
This is a good catch. The following theoretic derivation shows vMF kernel
and Euclidean distance are equivalent despite a scaling factor --

From Euclidean distance in the Gaussian kernel, we have
  exp(-delta^2/2 ||x-y||^2)
= exp(-delta^2/2 (x'*x+y'*y-2x'*y) )    % expanding
= exp(-delta^2/2 (1+1-2x'*y) )    % x'*x=1, y'*y=1, as they are L2
normalized
= exp(delta^2*x'*y -delta^2 )
= exp(delta^2*x'*y)/exp(delta^2)

This is proportional to  exp(delta^2*x'*y) by dropping the hyper-parameter
1/exp(delta^2)

The github script must be the initial version. But replace that Line 147
with S=S*S'

https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/blob/0abe46c053edb7579c65d1cc99673a6fa7239423/demo5_analysis_MShift_gradient/simulation07_1D_GBMS_1step_trajectory.m#L147


and Line 149 with  G = exp(0.5*S/(delta^2));

https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/blob/0abe46c053edb7579c65d1cc99673a6fa7239423/demo5_analysis_MShift_gradient/simulation07_1D_GBMS_1step_trajectory.m#L149

**Comment by utkarshgaur** [comment]
That explains it. Thanks for the clarification, Shu!
