### ISSUE TITLE
demo4 pascal voc instance segmenation SBD aug split

### ISSUE THREAD

**Issue by ahyunSeo** [aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping#7]
Hello,

I'm trying to run the train script of demo4.
I have total 11355(5623+5732) '.mat' annotations for SBD dataset,
 and 2913(1464+1449) '.png' annotation of VOCdevkit/VOC2012
In your imdb_complete_on_server.mat ,
 it seems like you use '.mat' annotations for VOC2012 also.

Did you convert '.png' annotations to '.mat' file to make it look like the ones for SBD?
Or is there some other trick that I didn't notice?
Also, could you give me a little explanation how the split 10582 / 1103 come from?
Sorry that I'm not familiar with this version of split.

Best regards, 

Ahyun

**Comment by aimerykong** [comment]
Hi, Ahyun,

Yes, I convert all annotations to the same format. For encoding the
instances, I don't think there are other tricks as this is a
straightforward engineering practice. Just make the annotations and images
paired well. Perhaps you need to pay attention to the background. I can't
remember what I did, but use the same label to annotate the background, say
using 0 value.

As the training set is a combination of VOC and SBD, while there are some
overlapping images between the two datasets, to merge them, I do the
following --

1. find the list of overlapping images in VOC2012 val set and SBD **ALL**
set, denoted by (2);
2. exclude set (2) from SBD **ALL** set -- this will be the complementary
training set (3);
3. merging set (3) and VOC2012 train set to form the final training set.
Note that if images in (3) are also included in VOC, do not merge them,
keep VOC annotation as it is finer than SBD.
Through the above procedure, you should get 10582 / 1103 split. This is a
common practice in literature.

Regards,
Shu

**Comment by ahyunSeo** [comment]
Thank you for your reply.
I'm sorry that I should have clarified my question.
I was wondering about the number 1103.
Including your paper, usually I see 10582 / 1449 split.
Could you tell me the difference between the split stated in your paper Section 5.1.?

Best,
Ahyun
